### PR TITLE
[#309] Add pygame as dependency

### LINKED ISSUE #309: Add `pygame` to requirements.txt
Pygame is used with JoyNode.py to allow a PS4 controller to send commands to the rover via ROS. It's only used in the base station. It isn't in the `requirements.txt` file however.

### PR DESCRIPTION
**Pull request by MartensCedric**
# Assignee Section

## Description
The joystick node doesnt work if you dont have pygame which isnt in the requirements.

- Added pygame as a library

closes #309 

The approval from all software team leads is necessary before merging.

# Reviewer Section

Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process.

- [x] Local Test Performed Successfully
- [ ] [General Integration Test](https://docs.google.com/document/d/1ug0CpA1cIzURP8DDFSvCt2CEJJSwJ6Ta6B1LG_hYk6I/edit) Performed Successfully

For Pull Requests that do not include code changes, it is not required to perform the tests above.

### CODE REVIEW

**Comment by vashmata** [comment]
We're gonna have to test this PR on a computer that's never successfully connected to the ps4 controller and moved the rover.

**Comment by adrientremblay** [comment]
Output before install requirements.txt:

rosrun mcu_control JoyNode.py
Traceback (most recent call last):
  File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 3, in <module>
    from Joy_class import Astro_Joy
  File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 3, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

Outputafter:

rosrun mcu_control JoyNode.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[INFO] [1584224876.283714]: Initialized joy_node for pub functionality
[INFO] [1584224876.284143]: Beginning to publish to /arm_command topic
[INFO] [1584224876.285102]: Beginning to publish to /rover_command topic
Traceback (most recent call last):
  File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 24, in <module>
    my_joy.switch()
  File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 395, in switch
    temp = self.controls.get_button(9)
pygame.error: Invalid joystick button

**Comment by MartensCedric** [comment]
> Output before install requirements.txt:
> 
> rosrun mcu_control JoyNode.py
> Traceback (most recent call last):
> File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 3, in
> from Joy_class import Astro_Joy
> File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 3, in
> import pygame
> ModuleNotFoundError: No module named 'pygame'
> 
> Outputafter:
> 
> rosrun mcu_control JoyNode.py
> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> [INFO] [1584224876.283714]: Initialized joy_node for pub functionality
> [INFO] [1584224876.284143]: Beginning to publish to /arm_command topic
> [INFO] [1584224876.285102]: Beginning to publish to /rover_command topic
> Traceback (most recent call last):
> File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 24, in
> my_joy.switch()
> File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 395, in switch
> temp = self.controls.get_button(9)
> pygame.error: Invalid joystick button

@Waleed-HM can you confirm this is the normal behavior when you run the node without a joystick connected? We should maybe open an issue to _not_ crash if that's the case and maybe allow it to wait for a connection

**Comment by Waleed-HM** [comment]
@adrientremblay 
Do you have a PS4 joystick connected to the PC when you run the script ?

**Comment by adrientremblay** [comment]
@Waleed-HM  nope.  I do not have one for testing purposes unfortunately.

**Comment by vashmata** [comment]
> > Output before install requirements.txt:
> > rosrun mcu_control JoyNode.py
> > Traceback (most recent call last):
> > File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 3, in
> > from Joy_class import Astro_Joy
> > File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 3, in
> > import pygame
> > ModuleNotFoundError: No module named 'pygame'
> > Outputafter:
> > rosrun mcu_control JoyNode.py
> > pygame 1.9.6
> > Hello from the pygame community. https://www.pygame.org/contribute.html
> > [INFO] [1584224876.283714]: Initialized joy_node for pub functionality
> > [INFO] [1584224876.284143]: Beginning to publish to /arm_command topic
> > [INFO] [1584224876.285102]: Beginning to publish to /rover_command topic
> > Traceback (most recent call last):
> > File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 24, in
> > my_joy.switch()
> > File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 395, in switch
> > temp = self.controls.get_button(9)
> > pygame.error: Invalid joystick button
> 
> @Waleed-HM can you confirm this is the normal behavior when you run the node without a joystick connected? We should maybe open an issue to _not_ crash if that's the case and maybe allow it to wait for a connection

I obtain a different error when it's not connected:
```
Traceback (most recent call last):
  File "/home/vashmata/Programming/git/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 19, in <module>
    my_joy = Astro_Joy(40,30,True)
  File "/home/vashmata/Programming/git/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 69, in __init__
    self.controls = pygame.joystick.Joystick(0)
pygame.error: Invalid joystick device number
```

**Comment by MartensCedric** [comment]
> > > Output before install requirements.txt:
> > > rosrun mcu_control JoyNode.py
> > > Traceback (most recent call last):
> > > File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 3, in
> > > from Joy_class import Astro_Joy
> > > File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 3, in
> > > import pygame
> > > ModuleNotFoundError: No module named 'pygame'
> > > Outputafter:
> > > rosrun mcu_control JoyNode.py
> > > pygame 1.9.6
> > > Hello from the pygame community. https://www.pygame.org/contribute.html
> > > [INFO] [1584224876.283714]: Initialized joy_node for pub functionality
> > > [INFO] [1584224876.284143]: Beginning to publish to /arm_command topic
> > > [INFO] [1584224876.285102]: Beginning to publish to /rover_command topic
> > > Traceback (most recent call last):
> > > File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 24, in
> > > my_joy.switch()
> > > File "/home/adrien/Programming/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 395, in switch
> > > temp = self.controls.get_button(9)
> > > pygame.error: Invalid joystick button
> > 
> > 
> > @Waleed-HM can you confirm this is the normal behavior when you run the node without a joystick connected? We should maybe open an issue to _not_ crash if that's the case and maybe allow it to wait for a connection
> 
> I obtain a different error when it's not connected:
> 
> ```
> Traceback (most recent call last):
>   File "/home/vashmata/Programming/git/robotics-prototype/robot/rospackages/src/mcu_control/scripts/JoyNode.py", line 19, in <module>
>     my_joy = Astro_Joy(40,30,True)
>   File "/home/vashmata/Programming/git/robotics-prototype/robot/rospackages/src/mcu_control/scripts/Joy_class.py", line 69, in __init__
>     self.controls = pygame.joystick.Joystick(0)
> pygame.error: Invalid joystick device number
> ```

This is also what I get.

**Comment by Waleed-HM** [comment]
it's very weird to give an error on that specific line which many more similar lines before it. I'm not sure.

**Comment by Waleed-HM** [comment]
@vashmata @adrientremblay 
Oh, I think I know why you get a different error. 
The Joy_Node is getting the error at a line after the line that calls an instance of the Joy Class.
If there's no joystick, that line should give you the error ( the one that Josh has ). 
Do you have a wireless mouse or keyboard connected to your PC ? the Pygame library might recognize it as a Joystick device. The Pygame library is not specific to the PS4 controller. 

Overall, I wouldn't worry about this error . I can approve this merge.

**Pull request merged**
