### PR TITLE
Add aliases to the install_ros_kinetic script 

### LINKED ISSUE #393: Add catkin aliases to "install_ros_kinetic" script
When I pushed a fix for the installation scripts, I remove some catkin aliases that are pretty useful. 
This issue is to re-add them.

### PR DESCRIPTION
**Pull request by AFknUsername**
# Assignee Section

## Description
Add the 2 aliases
Fix some potential errors

### Steps for Testing
1. Copy paste this into an executable file that you create (don't forget to set it as executable):
```
#!/bin/bash

sh -c "echo \"\n\n#------ POST ROS INSTALLATION ------\" >> testfile"
sh -c "echo \"alias eb='nano ~/testfile'\" >> testfile"
sh -c "echo \"alias sb='source ~/testfile'\" >> testfile"
sh -c "echo \"alias gs='git status'\" >> testfile"
sh -c "echo \"alias gp='git pull'\" >> testfile"
sh -c "echo \"\nalias cw='cd ~/Programming/robotics-prototype/robot/rospackages/'\" >> testfile"
sh -c "echo \"alias cm='cw && catkin_make'\" >> testfile"
sh -c "echo \"\nexport ROS_MASTER_URI=http://localhost:11311\" >> testfile"
sh -c "echo \"export ROS_HOSTNAME=localhost\" >> testfile"
```
**You might need to create the `testfile` for it to work**
2. run the script
3. check that the output in `testfile` is correct (the 2 new lines at the top are intentional)

The script is the same code just with a different output file.

closes #393 

The approval from all software team leads is necessary before merging.

# Reviewer Section

Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process.

- [x] Local Test Performed Successfully
- [ ] [General Integration Test](https://docs.google.com/document/d/1ug0CpA1cIzURP8DDFSvCt2CEJJSwJ6Ta6B1LG_hYk6I/edit) Performed Successfully

For Pull Requests that do not include code changes, it is not required to perform the tests above.

### CODE REVIEW

**Comment by AFknUsername** [comment]
Just tested this and it worked perfectly. Pls approve

**Comment by MartensCedric** [comment]
why dont you add them to the basestation/config/.bash_aliases or transfer everything here?

**Comment by MartensCedric** [comment]
> why dont you add them to the basestation/config/.bash_aliases or transfer everything here?

Seems to me that transferring everything here could be better since it would allow us to edit them and remove the ones we dont want.

What do you think @PeterGhimself

**Comment by PeterGhimself** [comment]
Aliases that should remain unchanged would go to either `.bash_aliases` in rover or basestation folders, depending on where they are meant to be used. The ones defined there tend to be more reliable if ever used in scripts.

**Pull request merged**
