### PR TITLE
Teensyduino libs install 362

### LINKED ISSUE #362: Automate Teensyduino library installs with CMake
We should have a section in the README explaining how to setup teensyduino as well as which libraries must be downloaded. Note that we should think how we would automate this.

### PR DESCRIPTION
**Pull request by steamypotato**
# Assignee Section

## Description
The CMake script in `robot/rover` installs all needed Teensyduino libraries, using `install_libraries.sh` in `robot/rover`. By default, Arduino libraries are installed in `~/Arduino/libraries`, so this script won't work if someone changed the default installation directories of the Arduino IDE.

### Steps for Testing
1. Delete all libraries in `~/Arduino/libraries` (except for unrelated libraries installed for personal use)
2. Go to `robotics-prototype/robot/rover` 
3. `mkdir build && cd build`
4. `cmake ..` and ensure that the library installations are logged in the terminal. 
5. `make` 

closes #362 

The approval from all software team leads is necessary before merging.

# Reviewer Section

Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process.

- [x] Local Test Performed Successfully
- [ ] [General Integration Test](https://docs.google.com/document/d/1ug0CpA1cIzURP8DDFSvCt2CEJJSwJ6Ta6B1LG_hYk6I/edit) Performed Successfully

For Pull Requests that do not include code changes, it is not required to perform the tests above.

### CODE REVIEW

**Comment by MartensCedric** [comment]
```
Picked up JAVA_TOOL_OPTIONS: 
java.lang.NullPointerException
	at cc.arduino.contributions.packages.ContributionsIndexer.parseIndex(ContributionsIndexer.java:124)
	at processing.app.BaseNoGui.initPackages(BaseNoGui.java:505)
	at processing.app.Base.<init>(Base.java:268)
	at processing.app.Base.main(Base.java:151)
```

I can't open my IDE anymore...

https://forum.arduino.cc/index.php?topic=565263.0

**Comment by NinjaWeeaboo** [comment]
Wait, idk if this is just an issue on my end, but I get this when I launch Arduino IDE with the terminal.
image

This seems to be related to the `~/.arduino15` like how @MartensCedric error is, I'll do a bit of investigating on my end too.

**Comment by NinjaWeeaboo** [comment]
That error did stop me from launching the Arduino IDE the first time I ran it from the terminal

**Comment by MartensCedric** [comment]
> Wait, idk if this is just an issue on my end, but I get this when I launch Arduino IDE with the terminal.
> image
> 
> This seems to be related to the `~/.arduino15` like how @MartensCedric error is, I'll do a bit of investigating on my end too.

The GTK errors can be ignored, you get the same thing using `telegram-desktop` on ubuntu

**Comment by PeterGhimself** [comment]
> ```
> Picked up JAVA_TOOL_OPTIONS: 
> java.lang.NullPointerException
> 	at cc.arduino.contributions.packages.ContributionsIndexer.parseIndex(ContributionsIndexer.java:124)
> 	at processing.app.BaseNoGui.initPackages(BaseNoGui.java:505)
> 	at processing.app.Base.<init>(Base.java:268)
> 	at processing.app.Base.main(Base.java:151)
> ```
> 
> I can't open my IDE anymore... Can you open your arduino IDE?
> 
> https://forum.arduino.cc/index.php?topic=565263.0

After switching around a few branches, I finally encountered this issue too. Had to delete the `.arduino15` folder to be able to open it again :thinking:

**Comment by MartensCedric** [comment]
What about the IDE problem @AFknUsername? Can you :eye: to see if you have
it?

**Comment by AFknUsername** [comment]
I can open CLion, if i choose the robotics-prototype as the project I get a CMake error that says that the robot directory doesn't contain a CMakeLists.txt file. 

I can also open the arduino IDE no problem.

**Pull request merged**
