### PR TITLE
Migrate melodic 422

### LINKED ISSUE #422: Migration to melodic
This issue will keep track of the progress to migrate to melodic.

- [x] venv works
- [x] all pip packages are ok
- [ ] all ros packages are ok
- [x] everything builds on cmake
- [x] update travis-ci to build on bionic
- [x] update submodules

### LINKED ISSUE #430: Find a replacement for `ifconfig` in env.sh to not have to download an extra package during setup
The ifconfig command has been deprecated in 18.04 and needs to be replaced. 
Good candidate for replacement: `ip a`

### PR DESCRIPTION
**Pull request by AFknUsername**
# Assignee Section

## Description
This PR fast-tracks the migration to Ubuntu 18.04.
Members who upgrade to bionic simply have to execute `EnvironmentSetup.sh`  to get started.

### Changes
1. Install scripts updated to install melodic for bionic, and refactor the scripts into more logical roles.
2. README updated to reflect changes in setup process.
3. travis-ci config changed to reflect the changes to bionic. 
4. submodules updated.

### Steps for Testing
1. Upgrade to bionic (always preferably a fresh install)
2. **GIT CHECKOUT MIGRATE-MELODIC-422**
2. Follow the steps in the README (preferably use the script)

closes #422 
closes #430 

The approval from all software team leads is necessary before merging.

# Reviewer Section

Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process.

- [ ] Local Test Performed Successfully
- [ ] [General Integration Test](https://docs.google.com/document/d/1ug0CpA1cIzURP8DDFSvCt2CEJJSwJ6Ta6B1LG_hYk6I/edit) Performed Successfully

For Pull Requests that do not include code changes, it is not required to perform the tests above.

### CODE REVIEW

**Comment by AFknUsername** [comment]
Thanks gamer @RealWilliamWells 😎 
It's very weird that you had to run the script twice for the python packages. I used it on a fresh install and it was all fine..
Also, every time you run the script it edits your bash files (bashrc and bash_aliases), you should take a look cause they might be messy. 👍

**Comment by KoaTheKoala** [comment]
I've tried testing the the setup script, but I'm having an issue.

Starting with a fresh install of Ubuntu 18.04, I tried running the original setup script (for ROS melodic) and encountered obvious issues. I deleted the repository, removed all changes to .bashrc, and deleted .bash_aliases.

I then recopied the repository, checked out this branch, and tried running the setup script. Everything worked fine up until the ros-melodic-desktop-full install line.

Also, when opening a new terminal, I getting the following error:
"Programming/robotics-prototype/robot/rospackages/devel/setup.bash"

I believe this error is caused by the failed ROS install (no catkin_make command gets run).

image

**Comment by KoaTheKoala** [comment]
William had a similar issue and recommended running the setup script twice. I tried this, but ended up with the same errors.

**Comment by RealWilliamWells** [comment]
I just tested again and ran into the same issue as before, and managed to get screenshots of the errors I encountered. I still don't really know why this happens, will be doing some more investigating.

Screenshot (33)

**Comment by KoaTheKoala** [comment]
With the assistance of Mr. Tim himself, we were able to resolve my issue. Mine was caused by what was likely a residual text file change from running the kinetic setup script.

Specifically the issue was with ~/etc/apt/sources.list.d/ros-latest.list~

The file contained
"deb http://packages.org/ros/ubuntu xenial main"

For those that don't know, xenial refers to Ubuntu 16.04. Changing xenial to bionic for Ubuntu 18.04 resolved the issue.

No one should experience this issue if they run the setup script from this branch on a fresh install of Ubuntu 18.04.

**Comment by RealWilliamWells** [comment]
Alrighty, so this doesn't make any sense, but the only way I've been able to fix this is by adding "python3-venv" to the list of packages to install. For some bizarre reason, if "python3-venv" isn't installed before trying to create a venv, the terminal has to be restarted. I've tested this on many other fresh installs with the same result. So perhaps I must be doing something wrong?

**Comment by AFknUsername** [comment]
The last commits fix @RealWilliamWells issues.
The fix was to install the python3-pip package before creating the virtual environment.

**Comment by MartensCedric** [comment]
Unfortunately I closed the terminal because I saw that it was complete, but when I opened a new one. it couldnt find

`/home/cedric/Programming/robotics-prototype/robot/rospackages/devel/setup.bash`

**Comment by MartensCedric** [comment]
I RAN MASTER LMAO

**Comment by MartensCedric** [comment]
```
..
Setting up ros-melodic-librviz-tutorial (0.10.5-1bionic.20200624.182449) ...
Setting up ros-melodic-simulators (1.4.1-0bionic.20200624.183757) ...
Setting up ros-melodic-urdf-tutorial (0.4.0-0bionic.20200624.182806) ...
Setting up ros-melodic-urdf-sim-tutorial (0.4.0-0bionic.20200624.183708) ...
Setting up ros-melodic-viz (1.4.1-0bionic.20200624.184031) ...
Setting up ros-melodic-visualization-tutorials (0.10.5-1bionic.20200624.183555) ...
Setting up ros-melodic-desktop (1.4.1-0bionic.20200624.184107) ...
Setting up ros-melodic-desktop-full (1.4.1-0bionic.20200624.184153) ...
Processing triggers for libc-bin (2.27-3ubuntu1.2) ...
[Initialize rosdep and install dependencies]
sh: 1: rosdep: not found
install_ros.sh: line 48: rosdep: command not found
install_ros.sh: line 49: rosdep: command not found
[Build ros packages using catkin]
install_ros.sh: line 53: /opt/ros//setup.bash: No such file or directory
install_ros.sh: line 54: cd: /robot/rospackages: No such file or directory
install_ros.sh: line 55: catkin_make: command not found
[Environment setup and getting rosinstall]
Reading package lists... Done

```

**Comment by AFknUsername** [comment]
Turns out rosdep was not installed by default anymore so it had to be added manually.
Also I messed up a few things when refactoring, all of it is fixed too
@MartensCedric

**Comment by AFknUsername** [comment]
@KoaTheKoala @RealWilliamWells @Gmartinica 
All of you should run the setup again to make sure that everything is ok. Most likely the setup did not complete successfully since I just caught a pretty serious error. 

After you run the script, your .bashrc and .bash_aliases files will have duplicate sections, which you should remove (it wont cause issues but it's good to keep it clean)

**Comment by RealWilliamWells** [comment]
Good job! Just tested the setup script on a VM, and everything seemed to have installed just fine without any issues. The GUI and arduino IDE with all its libraries, run without any issues. Something I've noticed tho, is that you forgot to update the closing message in the setup, it still says kinetic instead of melodic. 

Additionally I honestly don't believe this to be to the fault of the setup script, but I think it's still worth bringing up. I get this error when running `startgui`:
image
Which is weird, considering I thought `ifconfig` was something that came with ubuntu. This doesn't seem to affect running the GUI locally tho. It can also be fixed just by installing net-tools which comes with ifconfig.

**Comment by AFknUsername** [comment]
Thanks gamer @RealWilliamWells 
It seems like ifconfig got removed from 18.04.
I didn't catch this error since I have the ubuntu server installed and had to install extra packages to get full functionality. 
I probably installed net-tools to handle wifi.

A replacement command for `ifconfig` can be `ip a`

**Comment by AFknUsername** [comment]
@MartensCedric @PeterGhimself 
It seems like python3.6 is prepackaged with ubuntu 18.
Would it be ok to remove the addition of the PPA for ubuntu and use the one that comes with bionic?

**Comment by MartensCedric** [comment]
yup

**Comment by Gmartinica** [comment]
Tried the PR with a fresh install of Bionic in a virtual machine and everything seems to be working fine! I ran pytest, ran the GUI and even started recording myself. 
The only things I would point out like @RealWilliamWells William mentioned is that at the end of the installation it says you installed ROS kinetic and not melodic. 
Also got the same error of the `ifconfig` command, which does not come by default and has to be installed with net-tools or you might need to change it to `ip a`

Overall, nice job!

Screen Shot 2020-07-29 at 9 28 26 PM

**Comment by AFknUsername** [comment]
@Gmartinica Thanks for the feedback!

**Pull request merged**
