### PR TITLE
Joy node 545

### LINKED ISSUE #545: Create custom mappings for joystick controls.
We would like to be able to have custom joystick mappings for different people. 
We would also like different mappings for arm and wheel controls and to be able to switch between both using a button.

### LINKED ISSUE #573: Move multiple arm motors at the same time
Collect input and then publish a combined Arm command  (set_motor_speeds p p p p p p) that allows for controlling different motors without effecting each other.

### Current situation:
publishing a command for a certain motor implies that all other motors shall not move. This happens because button input is mapped to an Arm command with a default value of 0 (no movement) except the motor in question. This means if two buttons, for two different motors, are pressed, both motors will try to move but also stop the other motor from moving.

### Success criteria
Being able to move multiple Arm motors at the same time using a controller by pressing buttons or moving joysticks.

### UX
User should find it easy to control the Arm and switch between different layouts to perform basic Arm movement actions sussccefully.

### PR DESCRIPTION
**Pull request by AymanShe**
# Assignee Section

## Description
Create the ability to change the layout of the joystick controller by changing a configuration file without changing the code.

- Create a node that reads from Joy Node and publishes Arm Commands and Rover Commands(Wheel).
- Node reads from a Yaml configuration file that has the mapping of buttons to commands.

### Steps for Testing
1. Run ros core.
2. Connect the controller via USB.
3. Run Joy Node.
4. Run mcu controller node.
5. Echo the Arm topic.
6. Echo the Rover topic.
7. Press buttons on the controller and watch the arm and rover commands being published.
8. Switch between Arm and Wheel with select and share buttons.
[Needs more details]
When testing on the rover arm and wheel should move.

closes #545 
closes #573 

The approval from all software team leads is necessary before merging.

# Reviewer Section

Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process.

- [ ] Local Test Performed Successfully
- [ ] [General Integration Test](https://docs.google.com/document/d/1ug0CpA1cIzURP8DDFSvCt2CEJJSwJ6Ta6B1LG_hYk6I/edit) Performed Successfully

For Pull Requests that do not include code changes, it is not required to perform the tests above.

### CODE REVIEW

**Review by VimFreeman — APPROVED** [review]
Good to merge

**Comment by AymanShe** [comment]
After meeting today, we agreed to merge this PR, but immediately implement **combined command**s to allow for moving multiple "Arm" motors at the same time (either by creating a new issue or reopening this one). 

Immediately after that, refactor the code and remove all unnecessary logic, simplify the functionality of the node, reformat the code for easier readability. 

If the **Action Based** new issue #572 can be done with less effort than refactoring, the refactoring issue won't be created, but all aspects of clean, simple, and maintainable code shall be a requirement of the  **Action Based* issue.

Bugs that show up in this PR have the highest priority over all mentioned.

**Comment by AymanShe** [comment]
I added the compound command in another branch and merged with this to be merged together.
I tested my new changes today and they work fine.

**Review by VimFreeman — APPROVED** [review]
Changes look fine, only needs to be tested before merging

**Comment by RealWilliamWells** [comment]
I intend to test this locally today as well to see the output of the controller node on the command topics. After I test that out I'll approve and it'll be gucci for merging.

**Review by RealWilliamWells — APPROVED** [review]
Tested locally and worked perfectly for compounding commands.

**Pull request merged**
