### PR TITLE
[#00] Update changes from gitlab

### PR DESCRIPTION
**Pull request by NichHarris**

### CODE REVIEW

**Comment by PeterGhimself** [comment]
Are you using the commit prepender hook?

**Comment by NichHarris** [comment]
Yes I am.

**Comment by MartensCedric** [comment]
The change itself here is fine but the commit `cea1c1` is not in the master branch of Gitlab @NichHarris . I would assume an ideal process would be to PR on GitLab your changes and once it is in master we can do stuff on GH. This way, we will always have Gitlab's master code and never have independent commits that are referred to.

**Comment by MartensCedric** [comment]
Were the changes made to GL?

**Comment by NichHarris** [comment]
> Were the changes made to GL?

Created the PR. Will update you when it is approved.

**Comment by NichHarris** [comment]
@MartensCedric Requested changes were made to GL. 
rover2018-elec master was pulled down into the GH submodule in latest commit.

**Comment by MartensCedric** [comment]
You didn't update with GL master properly. I'm not sure how you did it, but I made a commit to fix it, to make sure it points to GL master. Your commit was pointing to `0f0bfa` and I couldn't find that.

Anyway, it's fixed now. Eventually, we will automate it to be synced with #198. 


image

**Pull request merged**
