### PR TITLE
Docker camera 474

### LINKED ISSUE #474: Camera working in docker
Currently the camera does not seem to work inside of docker. Additional work should be done such that a camera such as a webcam should be able to be displayed in docker

### PR DESCRIPTION
**Pull request by MewtR**
# Assignee Section

## Description
This PR gets the stream (camera) working in docker. 

Note: Edits were made to the Dockerfile which means that the docker build process will take a significant amount of time (~2 hours) even if it was built previously.

### Steps for Testing

1. Run the project with docker using docker-compose up --build or follow the README instructions in the docker directory if it's your first time.
2. Visit `http://localhost:5000`
3. `Stream Select` > `/dev/video0` (It might take a few seconds before you can see `/dev/video0` in the dropdown menu)
4. Click the power button. The stream should start. If it doesn't, wait a few seconds and then try selecting the `/dev/video0` stream again (without hitting the power button this time).

#### Optional additional steps

1. With the project running in docker, visit `http://localhost:8080`
2. Click on `image_raw` to get a stream or `Snapshot` to get a picture. 

closes #474 

The approval from all software team leads is necessary before merging.

# Reviewer Section

Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process.

- [x] Local Test Performed Successfully
- [ ] [General Integration Test](https://docs.google.com/document/d/1ug0CpA1cIzURP8DDFSvCt2CEJJSwJ6Ta6B1LG_hYk6I/edit) Performed Successfully

For Pull Requests that do not include code changes, it is not required to perform the tests above.

### CODE REVIEW

**Review by MartensCedric — APPROVED** [review]
Works great!

**Comment by MartensCedric** [comment]
@AFknUsername can you review this?

**Comment by AFknUsername** [comment]
This is what I get when I try to access localhost:5000

@MewtR

**Review by AFknUsername — APPROVED** [review]
After messing around with it, I figured out that the issue is that brave was set to automatically upgrade requests to https (which is why the requests looked so weird).
I downloaded chromium and everything worked fine. even did the optional steps.
All good :+1:

**Pull request merged**
