### PR TITLE
[#311] Logging function behaving similarly to appendToConsole()

### LINKED ISSUE #311: roslibjs logging functions need parameter for deciding to print to chrome console
Currently the custom js ROS logging functions I made print to the chrome console by default. This issue will make the logging functions behave like `appendToConsole()`.

- [x] The logging functions have parameters that let us choose whether to print to gui and/or dev console

### PR DESCRIPTION
**Pull request by vashmata**
# Assignee Section

## Description
I made my logging functions behave more like Peter's `appendToConsole()` function. `logDebug()` up to `logFatal()`.

Steps to test:
1) Start the GUI with `rosgui` and `startgui`
2) Go to `localhost:5000` in chrome, open the dev console (`F12`)
3) Call the different logging functions (logDebug, logInfo, logWarn, logErr, logFatal) with a message and one or two boolean parameters. Compare with how the `appendToConsole()` method behaves, they should print to the same consoles according to the boolean flags passed, though appendToConsole should not generate any roslogs. Use `rostopic echo /rosout` to monitor roslogs.

closes #311

The approval from all software team leads is necessary before merging.

# Reviewer Section

Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process.

- [x] Local Test Performed Successfully
- [ ] [General Integration Test](https://docs.google.com/document/d/1ug0CpA1cIzURP8DDFSvCt2CEJJSwJ6Ta6B1LG_hYk6I/edit) Performed Successfully

For Pull Requests that do not include code changes, it is not required to perform the tests above.

### CODE REVIEW

**Comment by vashmata** [comment]
Sorry, I closed this because it looked weird that when I was merging this branch it showed that I was merging a single commit.

**Comment by vashmata** [comment]
https://www.youtube.com/watch?v=E-TRR5zBLrI

**Comment by vashmata** [comment]
> I think in terms of classification this is the best I could come up. That said, I see one issue with my model. Debug should be at the lowest level. Programmers should set it to Debug and above and operators should use INFO and above (if debug is below INFO). In the current setup, this is not the case.

I don't understand your last paragraph
image

**Comment by MartensCedric** [comment]
> > I think in terms of classification this is the best I could come up. That said, I see one issue with my model. Debug should be at the lowest level. Programmers should set it to Debug and above and operators should use INFO and above (if debug is below INFO). In the current setup, this is not the case.
> 
> I don't understand this last paragraph
> image

Debug : Lowest Level (useful for programmers not useful for operators)
Info : Lowest Level for Operators. (useful for operators)

**Comment by MartensCedric** [comment]
Is it clear now? If not we can speak of it on Google Hangouts

**Comment by vashmata** [comment]
Are you saying that we should have an operator mode and a developer mode that will decide what the lowest debug level to be displayed is? Can't we already choose the lowest level in the javascript?

**Comment by MartensCedric** [comment]
Tested, seems to work

**Comment by PeterGhimself** [comment]
> https://www.youtube.com/watch?v=E-TRR5zBLrI

Oh, now I understand

**Pull request merged**
