### PR TITLE
Fix issue tag duplication 390

### LINKED ISSUE #390: Cherry Picking a commit will duplicate the [#ISSUE]
When you cherrypick a commit, it will duplicate the issue tag

See here : https://github.com/space-concordia-robotics/robotics-prototype/pull/389

### PR DESCRIPTION
**Pull request by NinjaWeeaboo**
# Assignee Section

## Description
Git commit message hook now checks for cherry-pick file that is present in '.git' folder during cherry picking. In order to avoid duplicating the issue number in the commit message. 

### Steps for Testing
1. Run `cp commit_message_hook.py .git/hooks/prepare-commit-msg` on 'fix-issue-tag-duplication-390' to cherry pick any older commit in branch, without pushing. (Use `git log` to view older commit hashes)
2. Use `git cherry-pick 613f09a` and run `git commit --allow-empty` to allow an empty commit. This still allows us to test if the hook will append the issue number to the message or not.
3. Check that the issue number wasn't duplicated in the commit message with `git commit --amend`.
4. Use `git reset HEAD^` to undo the commit. There shouldn't be any changes brought from the cherry pick if you used '613f09a', but if there are use `git stash` and `git stash drop` to delete the changes brought over.
5. Create a dummy file and commit it without pushing it, with a commit message of your choosing.
6. Ensure that the issue number was appended to the commit message with `git commit --amend`.
7. Use `git reset HEAD^` to undo the commit, then delete the dummy file.

closes #390

The approval from all software team leads is necessary before merging.

# Reviewer Section

Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process.

- [ ] Local Test Performed Successfully
- [ ] [General Integration Test](https://docs.google.com/document/d/1ug0CpA1cIzURP8DDFSvCt2CEJJSwJ6Ta6B1LG_hYk6I/edit) Performed Successfully

For Pull Requests that do not include code changes, it is not required to perform the tests above.

### CODE REVIEW

**Comment by AFknUsername** [comment]
So I'm trying to test this, but on step 2 when I try to cherry pick I get an error: 
Screen Shot 2020-06-06 at 9 46 48 PM
Is that to be expected?

**Comment by NinjaWeeaboo** [comment]
@AFknUsername Hmmm, I guess there must be merge conflicts from trying to cherry pick an older commit in the same branch. Could you try cherry picking a few other commits from master and see if that works? Thanks for test this my dude

**Comment by AFknUsername** [comment]
@NinjaWeeaboo It seems to work, but I am uncertain of the steps. 
Should we do git cherry-pick and then git commit -m?
Also in step 4, there are no changes to stash.
I feel like I'm missing something

**Comment by MartensCedric** [comment]
@AFknUsername You don't commit after cherry-picking

**Comment by MartensCedric** [comment]
When you cherry pick, it simply copies a commit from another branch into yours basically. A merge might be needed but not always

**Comment by AFknUsername** [comment]
@MartensCedric Ok, I get this: 
Screen Shot 2020-06-06 at 9 46 48 PM

Is that normal?

**Comment by MartensCedric** [comment]
> @NinjaWeeaboo It seems to work, but I am uncertain of the steps.
> Should we do git cherry-pick and then git commit -m?
> Also in step 4, there are no changes to stash.
> I feel like I'm missing something

assuming your git status was cleaned and you started following @NinjaWeeaboo's steps. I don't think you should have anything to stash @AFknUsername. You might wanna remove that will or explain

**Comment by MartensCedric** [comment]
I believe the commit you are cherry-picking is conflicting with your
branch, so you have to solve the merge by git adding shit together and then
committing. Now if you have nothing in the git status im a bit confused tho

**Comment by MartensCedric** [comment]
FYI @NinjaWeeaboo in your testing steps you should specify what exact commit we should test with, if someone has a problem like Tim, it becomes harder if we didnt follow the same steps

**Comment by MartensCedric** [comment]
@AFknUsername did you Cherry pick a commit in the same or another branch?

**Comment by MartensCedric** [comment]
So the reason it doesnt work @AFknUsername is that your CP a commit in the same branch. Take a commit in another branch like my travis branch, something not in master that wont conflict

**Comment by MartensCedric** [comment]
So the reason why it fails @AFknUsername, after my short investigation is that when you make a commit it only saves the diff. But the code where will's branch is, is so different then the diff, that it cant be applied.

Use this commit : 1ce4e530391e1df945afd9f00368635f582dd360

Youll have a merge but it should work

**Comment by MartensCedric** [comment]
@NinjaWeeaboo Ok last spam message, you might wanna revise the steps in the description since my example commit already had two [#ID] so you might wanna put in the steps a different commit to avoid confusing others

**Comment by NinjaWeeaboo** [comment]
Hey sorry guys for the confusion, I had to merge when I cherry picked so I had some changes carried over when I would undo the cherry pick. I'll find a good test commit to test with and update the description with it. 

@MartensCedric So in some cases when cherry picking should I actually make it add an issue number if there isn't already one? And also for if there's a different issue number already in the message?

**Comment by NinjaWeeaboo** [comment]
@AFknUsername If the cherry pick is empty it should be fine to use `git commit --allow-empty` as it will go through with the cherry pick and allow you to test anyways. I'll update the description with this as well.

**Comment by NinjaWeeaboo** [comment]
Alright gamers, try using hash '613f09a' and `git commit --allow-empty` to test this. I updated the description with this as well

**Comment by AFknUsername** [comment]
@NinjaWeeaboo I followed the steps and everything worked 👍 
@MartensCedric

**Pull request merged**
